spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/pharmacy_db
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5

    consumer:
      group-id: pharmacy-expiry-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  branch-name: Nha Thuoc So 1
  hotline: 1900xxxx

  kafka:
    stock-topic: medicine-stock-events

pharmacy:
  vat-rate: 0.20

warehouse:
  url: localhost:8082

insurance:
  url: localhost:8083

resilience4j:
  circuitbreaker:
    instances:
      warehouseCB:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 20s

      insuranceCB:
        failure-rate-threshold: 60
        minimum-number-of-calls: 5

  retry:
    instances:
      invoiceRetry:
        max-attempts: 3
        wait-duration: 2s

      insuranceRetry:
        max-attempts: 3
        wait-duration: 2s

  ratelimiter:
    instances:
      invoiceLimit:
        limit-for-period: 5
        limit-refresh-period: 10s
        timeout-duration: 0

  timelimiter:
    instances:
      insuranceTimeout:
        timeout-duration: 1s
